Fixed '-c add' overwriting existing app, added Discord update script

diff --git a/portappm b/portappm
--- a/portappm
+++ b/portappm
@@ -218,7 +218,7 @@ create_app_shortcut() {
     echo "$APP_NAME | Not a valid app, can't create shortcut!"
     exit 1
   fi
-  DESKTOP_FILE_DIR="/home/pavel/.local/share/applications/Portable"
+  DESKTOP_FILE_DIR="$HOME/.local/share/applications/Portable"
   APP_DESKTOP_FILE="$DESKTOP_FILE_DIR/$APP_NAME.desktop"
   if [[ -f "$APP_DESKTOP_FILE" ]]; then
     echo "Desktop file '$APP_DESKTOP_FILE' already exists."
@@ -289,6 +289,10 @@ create_all_app_shortcuts () {
 
 add_app () {
   local NEW_APP_NAME="$1"
+  if check_valid_app "$NEW_APP_NAME"; then
+    echo "App '$NEW_APP_NAME' can't be added, because already exists!"
+    exit 1
+  fi
   local NEW_APP_DIR="$APPS_DIRECTORY/$NEW_APP_NAME"
   DEFAULT_FILES_DIR="$(dirname "$(realpath "$0")")/default"
   NEW_APP_BASENAME="$(basename "$NEW_APP_DIR")"
